# Generated by Django 3.2 on 2022-04-05 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_socialmedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='github',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='linkedin',
        ),
        migrations.AddField(
            model_name='footer',
            name='social_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_media', to='home.socialmedia'),
        ),
    ]
