# Generated by Django 3.2 on 2022-04-05 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_footer_social_media'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nav',
        ),
    ]
