# Generated by Django 3.2 on 2022-04-05 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_delete_nav'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='subscribe',
        ),
    ]
