# Generated by Django 3.2 on 2022-04-06 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_footer_subscribe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmedia',
            old_name='icon',
            new_name='socialicon',
        ),
    ]
